config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :abouts, only:[:index]
  resources :products do
    resources :orders, only:[:index, :create]
    resources :comments, only:[:new, :create]
    collection do
      get 'search'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # mount_uploader :image, ImageUploader

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :condition
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipment_fee
  belongs_to_active_hash :shipment_term

  # 空の投稿を保存できないようにする
  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :image
    validates :quantity
    validates :explanation, length: { maximum: 300 }
  end

  # #ジャンルの選択が「--」の時は保存できないようにする
  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :condition_id
    validates :prefecture_id
    validates :shipment_term_id
    validates :shipment_fee_id
  end

  # priceの半角数字入力と数値の範囲指定
  validates :price, presence: true, format: { with: /\A-?[0-9]+(\.[0-9]+)?\z/, message: 'You must use half-width characters.' }, numericality: { only_integer: true, greater_than: 0 }

  # アソシエーション
  has_one_attached :image
  belongs_to :user
  has_one    :order
  has_many   :comments

  # 検索機能
  def self.search(search)
    if search != ""
      Product.where('text LIKE(?)', "%#{search}%")
    else
      Product.all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all.order("created_at DESC")
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_new_params)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
  end

  def edit
    unless current_user.id == @product.user_id
      redirect_to root_path
    end
  end

  def update
    if @product.update(product_new_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @product.user_id
    @product.destroy
    redirect_to root_path
    end
  end

  def search
    @products = Product.search(params[:keyword])
  end

  private

  def product_new_params
    params.require(:product).permit(:name, :image, :quantity, :price, :explanation, :category_id, :condition_id, :prefecture_id, :shipment_term_id, :shipment_fee_id).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%# cssはnew.cssを併用
app/assets/stylesheets/products/new.css %>

<%= render "shared/header" %>
<div class="products-sell-contents">
  <header class="products-sell-header">

  </header>
  <div class="products-sell-main">
    <h2 class="products-sell-title">商品の情報を入力</h2>
    <%= form_with model:@product, url:products_path, local: true do |f| %>
    <%= render 'shared/error_messages',locals: { message:@message }, model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"product-image" %>
      </div>
    </div>

    <%# 商品名と商品説明 %>
    <div class="new-products">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"products-text", id:"product-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      
      <div class="products-quantity">
        <div class="weight-bold-text">
          数量
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :quantity, class:"products-input", id:"product-quantity", placeholder:"単位まで入力してください。例）10kg,100本" %>
      </div>
      
      <div class="products-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"products-text", id:"product-info", placeholder:"商品説明（必須 1,000文字まで）（商品の状態、定価など）例）見た目は出荷基準以下ですが味・鮮度は出荷ひんと変わりません。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 商品の詳細 %>
    <div class="products-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"product-sales-status"}) %>
      </div>
    </div>

    <%# 配送について %>
    <div class="products-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipment_fee_id, ShipmentFee.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipment_term_id, ShipmentTerm.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
      </div>
    </div>

    <%# 販売価格 %>
    <div class="sell-price">
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"product-price", placeholder:"半角で入力して下さい" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/products/index.html.erb
<header class='top-page-header'>
  <div class="app-title">
    <h1 class="title is-1"><%= link_to 'Food Ecology', root_path, class: "title" %></h1>
  </div>

  
  <%= search_form_for @q do |f| %>
    <div class="search-form">
      <%= f.label :name, "商品検索", class: "search-title" %>
      <%= f.search_field :name_cont , placeholder: "商品名を入力", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    </div>
  <% end %>
  
  
  
  <div class="btn-list">
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <button><%= link_to '食品ロスとは', abouts_path, class: "about"  %></button>
        <button><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></button>
        <button><%= link_to '出品する', new_product_path, class: "sell-product" %></button>
      <% else %>
        <button><%= link_to '食品ロスとは', abouts_path, class: "about"  %></button>
        <button><%= link_to 'ログイン', new_user_session_path, class: "login" %></button>
        <button><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></button>
        <button><%= link_to '出品する', new_user_session_path, class: "sell-product" %></button><%#ログイン画面に遷移させる%>
      <% end %>
    </ul>
  </div>
</header>
<div class='main'>
  <div class="top-image">
    <%#= image_tag "top2.png" %>
  </div>
  <div class='title-contents'>
    <h2 class='catchphrase'>
      減らそう、食品ロス。
    </h2>
    <p class='service-explain'>
      FoodEcologyは、まだ食べられる食品を
    </p>
    <p class='service-explain'>
      販売してくれるお店や加工業者、消費者と繋ぐアプリです。
    </p>
  </div>
  <%# コンセプト %>
  <div class="app-concept">
    <h2 class="app-whats">what's Food Ecology</h2>
    <div class="app-explanation">
      <p>FoodEcologyは<span class="underline">「食品ロスを減らす」</span>というコンセプトの下に作られた、生産者と消費者を繋ぐアプリケーションです。</p>
      <p>当サイトでは賞味期限切れの商品も取り扱い、買い手・売り手は、個人法人問わず、誰でも出品・購入が可能です。</p>
      <p>在庫を抱え過ぎて賞味期限が切れてしまった商品や、傷やサイズの問題で出荷できなかった野菜など、</p>
      <p>何らかの理由で店頭に陳列することが出来なくなった商品は、<b>まだ安全に食べることができるのに、捨てられるしかありません。</b></p>
      <p>このような、いわゆる訳アリ商品を流通させることにより、<span class="underline">生産者や卸業者の廃棄コストが減り、消費者は安く購入できる</span>というメリットが生まれ、</p>
      <p>我々は、このアプリケーションを通じて食品ロスが減らし、環境負荷や経済損失といった社会問題の解消の一助になれればと考えております。</p>
    </div>
  </div>

  <%# 商品一覧表示 %>
  <div class="product-index">
    <div class="index-title">
      <h3>商品一覧（新着順）</h3>
    </div>
    <div class="product-lineup">
    <% @products.each do |product| %>
      <% if product.order == nil %>
        <li class='product-detail'>
          <%= link_to product_path(product) do %>
          <div>
            <%= image_tag product.image.variant(resize: '300x300'), class: "product-img" %>
          </div>
          <div class='product-info'>
            <p class='product-name'>
              <%= product.name %>
            </p> 
              <div class='product-quantity'>
                <%= product.quantity %>
              </div>
              <div class='product-price'>
                <span><%= product.price %>円(税込み)</span>
              </div>
            <div class='product-shipment-fee'>
              <%= product.shipment_fee.name %>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    <% end %>
    </div>
  </div>
</div>



<%= render "shared/footer" %>

app/views/products/new.html.erb
<%= render "shared/header" %>
<div class="products-sell-contents">
  <header class="products-sell-header">
  </header>
  <div class="products-sell-main">
    <h2 class="products-sell-title">商品の情報を入力</h2>
    <%= form_with model:@product, url:products_path, local: true do |f| %>
    <%= render 'shared/error_messages',locals: { message:@message }, model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"product-image" %>
        <div id="image-list"></div> <%# プレビュー %>
      </div>
    </div>

    <%# 商品名と商品説明 %>
    <div class="new-products">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"products-text", id:"product-name", placeholder:"商品名（必須 40文字まで)" ,rows:"2", maxlength:"40" %>
      
      <div class="products-quantity">
        <div class="weight-bold-text">
          数量
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :quantity, class:"products-input", id:"product-quantity", placeholder:"単位まで入力してください。" %>
      </div>
      
      <div class="products-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"products-text", id:"product-info", placeholder:"商品説明（必須 400文字まで）（商品の状態、定価など）" ,rows:"5" ,maxlength:"400" %>
      </div>
    </div>

    <%# 商品の詳細 %>
    <div class="products-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"product-sales-status"}) %>
      </div>
    </div>

    <%# 配送について %>
    <div class="products-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipment_fee_id, ShipmentFee.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipment_term_id, ShipmentTerm.all, :id, :name, {}, {class:"select-box", id:"product-category"}) %>
      </div>
    </div>

    <%# 販売価格 %>
    <div class="sell-price">
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"product-price", placeholder:"半角で入力して下さい" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/products/search.html.erb
<header class='top-page-header'>
  <div class="app-title">
    <h1 class="title is-1"><%= link_to 'Food Ecology', root_path, class: "title" %></h1>
  </div>

  <%= form_with(url: search_products_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "商品を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  
  <div class="btn-list">
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <button><%= link_to '食品ロスとは', abouts_path, class: "about"  %></button>
        <button><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></button>
        <button><%= link_to '出品する', new_product_path, class: "sell-product" %></button>
      <% else %>
        <button><%= link_to '食品ロスとは', abouts_path, class: "about"  %></button>
        <button><%= link_to 'ログイン', new_user_session_path, class: "login" %></button>
        <button><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></button>
        <button><%= link_to '出品する', new_user_session_path, class: "sell-product" %></button><%#ログイン画面に遷移させる%>
      <% end %>
    </ul>
  </div>
</header>

  <%# 商品一覧表示 %>
  <div class="product-index">
    <div class="index-title">
      <h3>検索結果（新着順）</h3>
    </div>
    <div class="product-lineup">
    
    </div>
  </div>
</div>

<%# 参考にsearch_appのコード %>
<h1>
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>
  <% @results.each do |result| %>
    <td>
    <br>
    <li>
      <%= result.name %>
      <%= result.size %>
      <%= result.status %>
      <%= result.price %>
      <%= result.category.name %>
    </li>
  <% end %>
<% else %>
  該当する商品はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>


<%= render "shared/footer" %>

app/views/products/show.html.erb
<%= render "shared/header" %>
<div class="show-image">
    <%#= image_tag "wood1.jpg", class:"show-image" %>
</div>
<%# 商品の概要 %>
<div class="product-show">
  <div class="product-box">
    <h2 class="name">
      <%= @product.name %>
    </h2>
    <div class='product-img-content'>
      <%= image_tag @product.image ,class:"product-box-img" %>
    </div>
    <div class="product-price-box">
      <p>価格： <span class="product-price"><%= @product.price %></span> 円</p>
      <span class="product-postage">
        (税込) 送料込み
      </span>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-product">商品名</th>
          <td class="detail-value"><%= @product.name %></td>
        </tr>
        <tr>
          <th class="detail-product">数量</th>
          <td class="detail-value"><%= @product.quantity %></td>
        </tr>
        <tr>
          <th class="detail-product">商品説明</th>
          <td class="detail-value"><%= @product.explanation %></td>
        </tr>
        <tr>
          <th class="detail-product">出品者</th>
          <td class="detail-value"><%= @product.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-product">カテゴリー</th>
          <td class="detail-value"><%= @product.category.name %></td>
        </tr>
        <tr>
          <th class="detail-product">商品の状態</th>
          <td class="detail-value"><%= @product.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-product">配送料の負担</th>
          <td class="detail-value"><%= @product.shipment_fee.name %></td>
        </tr>
        <tr>
          <th class="detail-product">発送元の地域</th>
          <td class="detail-value"><%= @product.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-product">発送日の目安</th>
          <td class="detail-value"><%= @product.shipment_term.name %></td>
        </tr>
      </tbody>
    </table>

    <% if @product.order == nil %>
      <%# ログインユーザーと出品ユーザーが、同一人物かどうかで表示を分ける%>
      <% if user_signed_in? && current_user.id == @product.user.id %>  
        <%= link_to '商品情報の編集', edit_product_path, method: :get, class: "buy-edit-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削 除', product_path, method: :delete, class:'product-destroy-btn' %>
      <% elsif user_signed_in? && current_user.id != @product.user.id %>
      <%# ログインユーザーと出品ユーザーが異なっていて、まだ商品が売れていない場合の表示 %>
        <%= link_to '購入画面に進む', product_orders_path(@product) ,class:"buy-edit-btn"%>
      <% end %>
    <% end %>
  </div>

<%# /商品の概要 %>
  <% if user_signed_in? %>
  <div class="comment-box">
    <%= form_with(model: [@product, @comment], local: true) do |form| %>
      <%= form.text_area :text, rows: "2",class:"comment-text" %>
      <%= form.submit "コメントする", class:"comment-btn" %>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <div class="comment-index">
    <div class="comment-title">
      <h3>＜コメント一覧＞</h4>
    </div>
    <% if @comments %>
      <% @comments.each do |comment| %>
        <p class="comment-sentence"> 
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>